// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAowXWLeG8WP_B7VqCwedr4HHuCuFeyvnw',
    appId: '1:783865588277:web:6397cb33f18a555786df7c',
    messagingSenderId: '783865588277',
    projectId: 'control-plus-c06a8',
    authDomain: 'control-plus-c06a8.firebaseapp.com',
    storageBucket: 'control-plus-c06a8.appspot.com',
    measurementId: 'G-RXNZC364ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJnTx1BLniTNsryE8kjslPLqQJZMktaXQ',
    appId: '1:783865588277:android:00c306210873c41986df7c',
    messagingSenderId: '783865588277',
    projectId: 'control-plus-c06a8',
    storageBucket: 'control-plus-c06a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqHY9uwsTfrJsAZ6KEwELslhnBHhj5vdM',
    appId: '1:783865588277:ios:bea9b75ace1e76f786df7c',
    messagingSenderId: '783865588277',
    projectId: 'control-plus-c06a8',
    storageBucket: 'control-plus-c06a8.appspot.com',
    iosClientId: '783865588277-qe43kuc3lt83447rjqhnjukmq9dbo7l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqHY9uwsTfrJsAZ6KEwELslhnBHhj5vdM',
    appId: '1:783865588277:ios:bea9b75ace1e76f786df7c',
    messagingSenderId: '783865588277',
    projectId: 'control-plus-c06a8',
    storageBucket: 'control-plus-c06a8.appspot.com',
    iosClientId: '783865588277-qe43kuc3lt83447rjqhnjukmq9dbo7l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestore',
  );
}
